apiVersion: v1
kind: Service
metadata:
  name: elrrdatasync-k8s-svc
spec:
  selector:
    app: elrrdatasync-k8s
    type: NodePort
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30037